<?php
$pagetitle = 'Marsel Mining';
include('includes/header.php');
include('includes/nav.php');
?>

  <!-- Begin page content -->
  <div class="container">
    <div class="page-header">
      <h1>Background</h1>
    </div>
    <p class="lead">Encompass Minerals (EncMin) is a privately-held resource development and engineering company.</p>
    <p>
      We have a dedicated team of experts in geology, mining, processing and metallurgy  located in Brazil, Ecuador, Peru, Colombia and Canada. EncMin’s main objective is to reduce the time lag required for the implementation of small to medium scale mining projects.  Our head office is located in Vancouver, Canada.  Where required, the company works with available research laboratories to conduct processing test work, model reserves and establish mine planning.  The time lag of a project is reduced when a minimum reserve is initially established and the cash flow generated by the development of this reserve supports the exploration of further areas.  This approach, based on the ideas of Fritz Shumacher, is internally referred to  as“Small Mining is Beautiful”.  Encompass believes that small  to medium scale operations can reduce the financial burden of the geological exploration and provides more certainty about the distribution of the mineral of interest  within given deposits.  EncMin also has a number of contacts with investors interested in the quick cash flow approach.  It is our philosophy to develop partnerships with our clients for the development of their projects, from green-field through to production where EncMin participates in the risk of the business, provides fair remuneration to our engineers (generally at our cost) during the development phases, in order to be remunerated with a percentage (e.g. 10%) of the production results of the mining operation.
    </p>
  </div>

<?php
include('includes/footer.php');
?>